extract setup and update steps from the run_api.sh script

diff --git a/run b/run
--- a/run
+++ b/run
@@ -5,7 +5,7 @@ API_URL="https://data.bioontology.org"
 STARTER_ONTOLOGY="STY"
 IMAGE_REPOSITORY="bioportal"
 IMAGE_TAG="latest"
-PROVISION=true  # Set the default value to true
+PROVISION=true # Set the default value to true
 
 # Function to display help message
 display_help() {
@@ -18,18 +18,24 @@ display_help() {
 # Parse command line options
 while getopts ":k:u:r:t:s:-:h" opt; do
     case $opt in
-        k) API_KEY="$OPTARG";;
-        u) API_URL="$OPTARG";;
-        r) IMAGE_REPOSITORY="$OPTARG";;
-        t) IMAGE_TAG="$OPTARG";;
-        s) STARTER_ONTOLOGY="$OPTARG";;
-        h) display_help;;
-        -) case "${OPTARG}" in
-               no-provision) PROVISION=false;;
-               help) display_help;;
-           esac;;
-        \?) echo "Invalid option: -$OPTARG" >&2; exit 1;;
-        :) echo "Option -$OPTARG requires an argument." >&2; exit 1;;
+    k) API_KEY="$OPTARG" ;;
+    u) API_URL="$OPTARG" ;;
+    r) IMAGE_REPOSITORY="$OPTARG" ;;
+    t) IMAGE_TAG="$OPTARG" ;;
+    s) STARTER_ONTOLOGY="$OPTARG" ;;
+    h) display_help ;;
+    -) case "${OPTARG}" in
+        no-provision) PROVISION=false ;;
+        help) display_help ;;
+        esac ;;
+    \?)
+        echo "Invalid option: -$OPTARG" >&2
+        exit 1
+        ;;
+    :)
+        echo "Option -$OPTARG requires an argument." >&2
+        exit 1
+        ;;
     esac
 done
 
@@ -42,8 +48,7 @@ fi
 
 echo "Running the Ontoportal API and CRON Setup..."
 
-
- # Copy .env.sample to .env
+# Copy .env.sample to .env
 if ! cp .env.sample .env; then
     echo "Error: Failed to copy .env.sample to .env."
     exit 1
@@ -75,7 +80,7 @@ echo "Updating IMAGE_TAG in .env file..."
 env_content="${env_content//IMAGE_TAG=latest/IMAGE_TAG=$IMAGE_TAG}"
 
 # Write the modified content back to the .env file
-echo "$env_content" > "$env_file_path"
+echo "$env_content" >"$env_file_path"
 
 # Step 8: Run provisioning
 if [ "$PROVISION" = true ]; then
@@ -87,40 +92,33 @@ if [ "$PROVISION" = true ]; then
     echo "Running provisioning ..."
     commands=(
         'docker compose  -f docker-compose_api.yml --profile 4store  down --volumes'
-        "bin/run_cron.sh $env_file_path 'bundle exec rake user:create[admin,admin@nodomain.org,password]'"
-        "bin/run_cron.sh $env_file_path 'bundle exec rake user:adminify[admin]'"
-        "bin/run_cron.sh $env_file_path 'bundle exec bin/ncbo_ontology_import --admin-user admin --ontologies $STARTER_ONTOLOGY --from-apikey $API_KEY --from $API_URL'"
-        "bin/run_cron.sh $env_file_path 'bundle exec bin/ncbo_ontology_process -o ${STARTER_ONTOLOGY}'"
+        "bin/run_cron.sh bundle exec rake user:create[admin,admin@nodomain.org,password]'"
+        "bin/run_cron.sh bundle exec rake user:adminify[admin]'"
+        "bin/run_cron.sh bundle exec bin/ncbo_ontology_import --admin-user admin --ontologies $STARTER_ONTOLOGY --from-apikey $API_KEY --from $API_URL'"
+        "bin/run_cron.sh bundle exec bin/ncbo_ontology_process -o ${STARTER_ONTOLOGY}'"
     )
 
     for cmd in "${commands[@]}"; do
         echo "> Run: $cmd"
         if ! eval "$cmd"; then
-          echo "Error: Failed to run provisioning .  $cmd"
-          exit 1
+            echo "Error: Failed to run provisioning .  $cmd"
+            exit 1
         fi
     done
 
     echo "Setup completed successfully!"
 fi
 
-
-
 echo "Running api ..."
 
-source bin/run_api.sh start
+bin/run_api.sh start
 
- # Wait for API to be ready (adjust the sleep time accordingly)
-timeout=300
-elapsed=0
-until [ $elapsed -ge $timeout ] || curl -sSf http://localhost:9393 > /dev/null 2>&1; do
-    echo "Waiting for the server to be up..."
-    sleep 1
-    elapsed=$((elapsed + 1))
-done
-if [ $elapsed -ge $timeout ]; then
-    echo "Timed out waiting for the server to be up."
+# Wait for API to be ready (adjust the sleep time accordingly)
+source utils/loading_animation.sh "[+] Waiting for the server http://localhost:9393 to be up..." "http://localhost:9393" 300
+
+if status_ok; then
+    echo "[+] API is up and running!"
+else
+    echo "[x] Timed out waiting for the server to be up."
     exit 1
 fi
-
-echo "Server is up and running!"
